### ISSUE TITLE
Camera Allow Option Not Pop Up

### ISSUE THREAD

**Issue by Saurabh6069** [kinghacker0/WishFish#1]
I Test In My Own Device Camera Allow or Block This Option No Pop Up Bro
Its Need To Allow Camera Menually From Site Settings Of Chrome.. Any solutions?

**Comment by kinghacker0** [comment]
Hi! Saurabh6069 thanks for your feedback we find out that this is not actual script problem this is browser problem.
When we send wishfish link to victim and victim open it in any other browser then chrome or inbuilt android browser the camera permissions pop up not showed because any third party browser doesn't have camera access that's why this problem occurs
